name:        primecount
version:     0.1.0.1
synopsis:    Bindings to the primecount library
github:      "pgujjula/primecount-haskell"
license:     BSD-3-Clause
author:      "Preetham Gujjula"
maintainer:  "libraries@mail.preetham.io"
copyright:   "2021 Preetham Gujjula"
category:    Math, Number Theory
description: Please see the README on Github at
             <https://github.com/pgujjula/primecount-haskell#readme>

tested-with: GHC ==8.10.7 || ==9.0.2 || ==9.2.8 || ==9.4.5 || ==9.6.2
extra-source-files:
- README.md
- ChangeLog.md

ghc-options:
- -Wall
- -Wcompat
- -Wmissing-export-lists
- -Wincomplete-record-updates
- -Wpartial-fields
- -Wmissing-home-modules
- -Werror=missing-home-modules
- -Widentities
- -Wredundant-constraints
- -Wmissing-export-lists

default-extensions:
- ScopedTypeVariables

dependencies:
- base >= 4.7 && < 5.0

library:
  source-dirs: src
  extra-libraries:
  - primecount
  exposed-modules:
  - Math.NumberTheory.Prime.Count
  - Math.NumberTheory.Prime.Count.FFI
  when:
  - condition: false
    other-modules: Paths_primecount

tests:
  primecount-tests:
    source-dirs: test
    main: Main.hs
    dependencies:
    - primecount
    - silently >= 1.2 && < 1.3
    - tasty >= 1.4 && < 1.5
    - tasty-hunit >= 0.10 && < 0.11
    other-modules:
    - Test.Math.NumberTheory.Prime.Count

benchmarks:
  primecount-bench:
    source-dirs: bench
    main: Main.hs
    dependencies:
    - primecount
    - tasty-bench >= 0.3 && < 0.4
    when:
    - condition: false
      other-modules: Paths_primecount
