# SPDX-FileCopyrightText: Copyright Preetham Gujjula
# SPDX-License-Identifier: BSD-3-Clause
verbatim:
  cabal-version: 3.6
name:         primecount
version:      0.1.0.2
synopsis:     Bindings to the primecount library
github:       "pgujjula/primecount-haskell"
license:      BSD-3-Clause
license-file: LICENSES/BSD-3-Clause.txt
author:       "Preetham Gujjula"
maintainer:   "libraries@mail.preetham.io"
copyright:    "Preetham Gujjula"
category:     Math, Number Theory
description:  Please see the README on Github at
              <https://github.com/pgujjula/primecount-haskell#readme>

tested-with: GHC == {8.10.7, 9.0.2, 9.2.8, 9.4.8, 9.6.6, 9.8.2, 9.10.1, 9.12.2}
extra-doc-files:
- README.md
- CHANGELOG.md

ghc-options:
- -Wall
- -Wcompat
- -Wmissing-export-lists
- -Wincomplete-record-updates
- -Wpartial-fields
- -Wmissing-home-modules
- -Werror=missing-home-modules
- -Widentities
- -Wredundant-constraints
- -Wmissing-export-lists

default-extensions:
- ScopedTypeVariables

dependencies:
- base ^>= {4.14, 4.15, 4.16, 4.17, 4.18, 4.19, 4.20, 4.21}

library:
  source-dirs: src
  extra-libraries:
  - primecount
  exposed-modules:
  - Math.NumberTheory.Prime.Count
  - Math.NumberTheory.Prime.Count.FFI
  when:
  - condition: false
    other-modules: Paths_primecount

tests:
  primecount-tests:
    source-dirs: test
    main: Main.hs
    dependencies:
    - primecount
    - silently ^>= {1.2}
    - tasty ^>= {1.4, 1.5}
    - tasty-hunit ^>= {0.10}
    other-modules:
    - Test.Math.NumberTheory.Prime.Count

benchmarks:
  primecount-bench:
    source-dirs: bench
    main: Main.hs
    dependencies:
    - primecount
    - tasty-bench ^>= {0.3, 0.4}
    when:
    - condition: false
      other-modules: Paths_primecount
